apiVersion: v1
kind: Secret
metadata:
    name: vsphere-cloud-secret
    labels:
        vsphere-cpi-infra: secret
        component: cloud-controller-manager
    namespace: kube-system
    # NOTE: this is just an example configuration, update with real values based on your environment
stringData:
    10.0.2.4.username: csi@vc.redacted.com
    10.0.2.4.password: 123password
